<!DOCTYPE html>
<html>
	<head>
		<title>PHP Fundamentals</title>
		<link rel="stylesheet" href="style.css" />
	</head>
	<body>
		<h1>PHP Fundamentals</h1>

<ul>
	<li>PHP is an open source server-side web scripting language. <strong>It requires a web server in order to function</strong>.</li>
	<li>Any file with PHP instructions requries the extension <code>.php</code></li>
	<li>HTML, CSS, and Javascript will commonly mingle with PHP code in the source files. End users will never see the PHP code (unlike client side technologies).</li>
	<li>PHP is case sensitive. Camel casing is the general style standard.</li>
	<li>In PHP, as in HTML CSS and Javascript, white space (tabs, spacebar spaces, carriage returns) in the code is ignored. Generally, each instruction begins on a new line, nested instructions are tabbed in</li>
	<li>Since PHP 4, PHP has supported Object Oriented Programming mechanisms.</li>
	<li>All php code must appear inside php declaration tags: <pre><code>&lt;?php

?&gt;
	</code></pre>	
	</li>
	
	<li>Comments (notes not processed by the server) for you and other developers. Use them to explain the logic of your PHP instructions, use them to declare authorship of your pages, use them to help organize and describe your code. They may be declared in a single or multi line format:<pre><code>//single comment line

/*
multi 
line 
comment
*/</code></pre>	
	</li>
	<li>Code consists of one or more instructions. All instructions terminate with a semicolon <code>;</code>. Instructions are occasionally bundled together using curly braces <code>{ }</code>
	</li>
	<li>As long as PHP instructions are placed inside php declaration tags, PHP can appear anywhere within an HTML. Try to ensure that any output generated by PHP results in valid HTML in the client's browser.</li>
	<li>The common PHP method for displaying output in the browser is <code>echo</code>. Follow the echo command with any series of characters in quotes or a numeric value.
<pre><code>//output the number 42
echo 42;

//output a series of characters
echo "Hello World";

//output as HTML
echo "&lt;h2>Hello World&lt;/h2>";
</code></pre>	
	</li>

</ul>
		
	</body>
</html>







